[package]
name = "RRD-Treadmill"
version = "1.0.0"
authors = ["Andrew Piroli"]
edition = "2018"
repository = "https://github.com/AndrewPiroli/RRD-Treadmill"
license = "MIT"

[dependencies]
regex="1"

[[bin]]
name = "rrd_treadmill"
path = "src/main.rs"